apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: akmaharshi.azurecr.io/akmaharshi/product-catalog-image:v${BUILD_NUMBER}
        ports:
        - containerPort: 8282
